### ISSUE TITLE
linovel is down due to copyright issue

### ISSUE THREAD

**Issue by pfei-sa** [bebound/linovel#17]
_(:з」∠)_

**Comment by bebound** [comment]
Well, my last commit make it possible to generate novel from other website.

**Comment by pfei-sa** [comment]
Just reviewed the code. In linovel.py line 52 why use 

``` python
for cls in [OldLinovel]:
```

**Comment by bebound** [comment]
Prepare for more class/website in the future.
Currently linovel only has one website rule.

**Comment by pfei-sa** [comment]
will all the rules store in the novel_oldlinovel.py file?

**Comment by bebound** [comment]
No, each website will create a new file `novel_xxx.py`, which contains a new class inherit from `AbstractNovel`. This files contains all the rules for the website.

**Comment by pfei-sa** [comment]
So `AbstractNovel` is kind of a template?

**Comment by bebound** [comment]
Yes, it provide a general interface, as each class has `check_url`,`extract_novel_information`,`get_novel_information` methods.
Then the epub class can use this information to generate epub file.

**Comment by pfei-sa** [comment]
Also why `novel_information` is a list

**Comment by bebound** [comment]
Because one url may contains several volumes of novels.

**Comment by pfei-sa** [comment]
I see, sorry for having so many questions. Thanks.

**Comment by Nriver** [comment]
Such a relief knowing that you will proceed. Kinda worried when found your blog is not accessalbe.

**Comment by pfei-sa** [comment]
linovel.com is back but old.linovel.com seems to be off line now. The content of the books are removed only some information about the books are left

**Comment by bebound** [comment]
@Nriver @tonyrft   I found `dmzj` is still available. Is there any other light novel website?

**Comment by pfei-sa** [comment]
@bebound http://ac.qq.com/Light is what I've found. But because it blocks foreign IP therefore I don't have detail. dmzj does offer light novel but the illustration in the book are usually missing or on separate page which will be hard to phase correctly.

**Comment by bebound** [comment]
Tencent offer light novel as images just like manga...

**Comment by pfei-sa** [comment]
Well... Maybe we can work on dmzj first.

**Comment by bebound** [comment]
Eh, I think generate a epub without any illustration makes no sense, but I'd like to merge it if you implement it.
