### ISSUE TITLE
bs4.FeatureNotFound: Couldn't find a tree builder with the features you request

### ISSUE THREAD

**Issue by eromoe** [bebound/linovel#28]
RT

```
(py3) E:\linovel>python linovel.py -s http://www.wenku8.com/book/200.htm
Traceback (most recent call last):
  File "linovel.py", line 91, in <module>
    sys.exit(main())
  File "linovel.py", line 84, in main
    start(urls, output_dir, cover_path, out_format)
  File "linovel.py", line 58, in start
    novel.extract_novel_information()
  File "E:\linovel\novel_wenku8.py", line 198, in extract_novel_information
    self.parse_vollist()
  File "E:\linovel\novel_wenku8.py", line 192, in parse_vollist
    soup = self.parse_page(self.url, 'gbk')
  File "E:\linovel\novel.py", line 62, in parse_page
    return BeautifulSoup(r.text, 'lxml')
  File "D:\Anaconda3\envs\py3\lib\site-packages\bs4\__init__.py", line 165, in _
_init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requeste
d: lxml. Do you need to install a parser library?
```

lxml 有装， 换成  html5lib 后变好了

OS： windows

**Comment by eromoe** [comment]
https://stackoverflow.com/questions/24398302/bs4-featurenotfound-couldnt-find-a-tree-builder-with-the-features-you-requeste

> For basic out of the box python with bs4 installed then you can process your xml with
> 
> soup = BeautifulSoup(html, "html5lib")
> If however you want to use formatter='xml' then you need to
> 
> pip3 install lxml
> 
> soup = BeautifulSoup(html, features="xml")

**Comment by bebound** [comment]
Double check `lxml` installed properly, it should work.

**Comment by eromoe** [comment]
OK, looks like `pip install lxml` is buggy in conda env.  I think maybe conda has lxml installed, then I use pip install update it cause lxml broken.
